spring:
  application:
    name: order-service

  # JPA & Database Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect

  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  # H2 Console Configuration (for development)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

# Server Configuration
server:
  port: ${SERVER_PORT:8083}

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
    # Configurare pentru porturi dinamice
    non-secure-port-enabled: true
    secure-port-enabled: false

# Monitoring and Metrics Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,configprops
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      environment: docker
  health:
    defaults:
      enabled: true
    db:
      enabled: true
    diskspace:
      enabled: true

# Logging Configuration
logging:
  level:
    com.unibuc: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Configurări specifice pentru business logic
restaurant:
  orders:
    max-items-per-order: 20
    timeout-minutes: 30
    currency: RON
  processing:
    async-enabled: true

# Service Info
info:
  app:
    name: Order Management Service
    description: Manages restaurant orders and order processing
    version: 1.0.0
