global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Eureka Server
  - job_name: 'eureka-server'
    static_configs:
      - targets: ['eureka-server:8761']
    metrics_path: '/actuator/prometheus'

  # Gateway Service (fixed port)
  - job_name: 'gateway-service'
    static_configs:
      - targets: ['gateway-service:8080']
    metrics_path: '/actuator/prometheus'

  # Config Server (fixed port)
  - job_name: 'config-server'
    static_configs:
      - targets: ['config-server:8888']
    metrics_path: '/actuator/prometheus'

  # Microservices with dynamic ports via Eureka Service Discovery
  - job_name: 'microservices-eureka'
    eureka_sd_configs:
      - server: http://eureka-server:8761/eureka
        refresh_interval: 30s
    relabel_configs:
      # Only scrape services that have actuator endpoints
      - source_labels: [__meta_eureka_app_name]
        regex: '(USER-SERVICE|MENU-SERVICE|ORDER-SERVICE|PAYMENT-SERVICE)'
        action: keep
      # Set the metrics path to actuator/prometheus
      - target_label: __metrics_path__
        replacement: /actuator/prometheus
      # Use the service name as job label (convert to lowercase)
      - source_labels: [__meta_eureka_app_name]
        target_label: job
        regex: '(.+)'
        replacement: '${1}'
      # Use instance ID as instance label
      - source_labels: [__meta_eureka_app_instance_id]
        target_label: instance
